version: '3.7'

services:

  frontend:
    container_name: docker-django-angular_frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4201:4200'
    environment:
      - CHOKIDAR_USEPOLLING=true