version: '2'  
services:  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    depends_on:
      - db
    volumes:
      - ./src:/src
    expose:
      - "80"
    links:
      - redis
  db:
    image: postgres:latest
  redis:
    image: redis:latest
    ports:
     - '6379:6379'
